version: '2'

services:
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
  bunnyacme:
    depends_on:
      - rabbitmq
    build: .
    hostname: bunnyacme
    volumes:
      - ../:/bunnyacme
    links:
      - rabbitmq
    command: php /bunnyacme/app/app.php queue:executor sleep
  push:
    depends_on:
      - rabbitmq
      - bunnyacme
    build: .
    hostname: bunnyacme-2
    volumes:
      - ../:/bunnyacme
    links:
      - rabbitmq
    command: php /bunnyacme/app/app.php dev:push
  logs:
    depends_on:
      - rabbitmq
    build: .
    hostname: bunnyacme-3
    volumes:
      - ../:/bunnyacme
    links:
      - rabbitmq
    command: php /bunnyacme/app/app.php dev:logs
        
        
