version: '2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 8080:15672
  worker1:
    depends_on:
      - rabbitmq
    build: .
    hostname: worker1
    volumes:
      - ../:/bunnyacme
    links:
      - rabbitmq
    command: php /bunnyacme/app/app.php queue:executor sleep

  worker2:
    depends_on:
      - rabbitmq
    build: .
    hostname: worker2
    volumes:
      - ../:/bunnyacme
    links:
      - rabbitmq
    command: php /bunnyacme/app/app.php queue:executor sleep

  push:
    depends_on:
      - rabbitmq
    build: .
    hostname: bunnyacme
    volumes:
      - ../:/bunnyacme
    links:
      - rabbitmq
    command: php /bunnyacme/app/app.php dev:push
  logs:
    depends_on:
      - rabbitmq
    build: .
    hostname: bunnyacme-3
    volumes:
      - ../:/bunnyacme
    links:
      - rabbitmq
    command: php /bunnyacme/app/app.php dev:logs